# Use the official Node.js image as the base image
FROM node:24-alpine

# Set the working directory inside the container
WORKDIR /nodejs-24

# Install git and other necessary tools
RUN apk add --no-cache git